name: "Release Pipeline"
on:
  push:
    branches:
      - v*
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
 
      - name: Cache Maven packages
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
 
      - name: "Set labels for ${{ github.ref }}"
        run: |
          echo "WEBGOAT_TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          WEBGOAT_MAVEN_VERSION=${{ github.ref_name }}
          echo "WEBGOAT_MAVEN_VERSION=${WEBGOAT_MAVEN_VERSION:1}" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          mvn --no-transfer-progress versions:set -DnewVersion=${{ env.WEBGOAT_MAVEN_VERSION }}
          mvn --no-transfer-progress install -DskipTests

      - name: "Docker Build Pull Request"
        if: github.event_name == 'pull_request'     
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            webgoat/webgoat:PR
          build-args: |
            webgoat_version=${{ env.WEBGOAT_MAVEN_VERSION }}

      - name: "Docker Build Release"
        if: startsWith(github.ref, 'refs/heads/v') && github.event_name == 'push'     
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            webgoat/webgoat:${{ env.WEBGOAT_TAG_VERSION }}
            webgoat/webgoat:latest
          build-args: |
            webgoat_version=${{ env.WEBGOAT_MAVEN_VERSION }}

      - name: Mend CLI Image Scan
        if: startsWith(github.ref, 'refs/heads/v') && github.event_name == 'push'
        env:
          MEND_EMAIL: ${{secrets.MEND_EMAIL}}
          MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
          MEND_URL: https://saas.mend.io
        run: |
          echo Downloading Mend CLI
          curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
          echo "Start Mend image scan"
          ./mend image webgoat/webgoat:${{ env.WEBGOAT_TAG_VERSION }} -s *//GH_${{github.event.repository.name}}//GH_${{github.event.repository.name}}_${{github.ref_name}}


            